version: '3.8'

services:
  web:
    build: ./services/web
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0"]
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5001:5000
      - 5678:5678
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=AirPIPD
      - POSTGRES_PASSWORD=AirPIPD
      - POSTGRES_DB=AirPIPD_dev

volumes:
  postgres_data:


